[package]
name = "bevy_web_wasm_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.17.3"
getrandom = { version = "0.3", features = ["wasm_js"] }

[profile.release]
opt-level = 'z'
lto = true
