[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.17.3"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
getrandom = { version = "0.3", features = ["wasm_js"] }
log = "0.4.29"

[profile.release]
opt-level = 'z'
lto = true
